apiVersion: v1
kind: Service
metadata:
  name: {{ template "og-kafka-mm.fullname" . }}
  labels:
    app: {{ template "og-kafka-mm.name" . }}
    chart: {{ template "og-kafka-mm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: kafka-mm
      port: {{ .Values.servicePort }}
    {{- if .Values.jmx.enabled }}
    - name: mm-monitoring
      port: {{ .Values.prometheus.jmx.port }}
    {{- end }}
  selector:
    app: {{ template "og-kafka-mm.name" . }}
    release: {{ .Release.Name }}
